name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4 
  dotenv: ^4.2.0
  mysql1: ^0.20.0
  get_it: ^8.0.3
  logger: ^2.5.0
  injectable: ^2.5.0
  jaguar_jwt: ^3.0.0
  http: ^1.0.0
  
  
dev_dependencies:  
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  shelf_router_generator: ^1.1.0
